services:
  - type: worker
    name: discord-selfbot
    runtime: python
    repo: https://github.com/kamirfelix23-boop/Online-Forever
    branch: main
    envVars:
      - key: DISCORD_TOKEN
        sync: true
      - key: STATUS_TEXT
        sync: true
